spring.application.name=backend
app.jwt.secret=your-256-bit-secret-change-this-in-production-make-it-long
app.jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/Chokho_AI
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

cloudinary.cloud-name=mannr075
cloudinary.api-key=611659275122399
cloudinary.api-secret=w2vdhkNxbhnf4WOPl1GjNom_MeU

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

spring.fastapi.routeUrl=http://localhost:8000/routes